import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

/*
 * Frontend workflow-record integration against the real local stack. It
 * creates a commission through the API, runs it to a decision, approves the
 * exact revision under review, publishes the record and verifies that the
 * public page renders the authoritative record. Enabled with E2E_STACK=1 and
 * the local credentials generated by `npm run local:env`.
 */

const API = process.env.E2E_API_URL || 'http://127.0.0.1:8080';

test.skip(
  process.env.E2E_STACK !== '1',
  'set E2E_STACK=1 with the local stack running',
);

async function api(token, path, options = {}) {
  const response = await fetch(API + path, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      ...(options.headers || {}),
    },
  });
  const body = await response.json();
  return { status: response.status, body };
}

async function waitForStage(token, id, stages, timeoutMs = 120000) {
  const deadline = Date.now() + timeoutMs;
  let last;
  while (Date.now() < deadline) {
    const { body } = await api(token, `/api/v1/workflows/${id}`);
    last = body;
    if (
      stages.includes(body.stage) &&
      (body.stage !== 'COMPLETED' || body.terminal)
    )
      return body;
    await new Promise((r) => setTimeout(r, 500));
  }
  throw new Error(
    `workflow ${id} never reached ${stages}; last ${JSON.stringify(last)}`,
  );
}

test('the History section renders a published record from the workflow service', async ({
  page,
}, testInfo) => {
  const access = JSON.parse(
    await readFile(resolve('.local/test-access.json'), 'utf8'),
  );
  const token = access.token;
  const created = await api(token, '/api/v1/commissions', {
    method: 'POST',
    headers: { 'Idempotency-Key': crypto.randomUUID() },
    body: JSON.stringify({
      brief: {
        title: `Record integration ${testInfo.project.name} ${Date.now()}`,
        objective:
          'Create an editorial identity for a cultural journal with clear hierarchy.',
        audience: 'Readers of contemporary culture',
        constraints: ['Accessible contrast'],
        prohibited: ['neon gradients'],
        brand_memory: [],
      },
    }),
  });
  expect(created.status).toBe(201);
  const id = created.body.id;
  expect(
    (await api(token, `/api/v1/commissions/${id}/start`, { method: 'POST' }))
      .status,
  ).toBe(202);
  const waiting = await waitForStage(token, id, ['WAITING_FOR_APPROVAL']);
  expect(waiting.pending_approval).toBeTruthy();

  // A decision naming a different revision is stale and refused with the
  // approval actually pending, so a client can refresh instead of guessing.
  const stale = await api(token, `/api/v1/workflows/${id}/decisions`, {
    method: 'POST',
    body: JSON.stringify({
      decision_id: crypto.randomUUID(),
      approval_id: waiting.pending_approval.id,
      revision_id: '00000000-0000-4000-8000-000000000000',
      action: 'APPROVE',
      reason_code: 'BRIEF_ALIGNED',
      reason: 'stale',
    }),
  });
  expect(stale.status).toBe(409);
  expect(stale.body.code).toBe('STALE_APPROVAL');
  expect(stale.body.pending_approval.revision_id).toBe(
    waiting.pending_approval.revision_id,
  );

  const decision = {
    decision_id: crypto.randomUUID(),
    approval_id: waiting.pending_approval.id,
    revision_id: waiting.pending_approval.revision_id,
    action: 'APPROVE',
    reason_code: 'BRIEF_ALIGNED',
    reason: 'Approved by the local test operator to verify the record.',
  };
  const signalled = await api(token, `/api/v1/workflows/${id}/decisions`, {
    method: 'POST',
    body: JSON.stringify(decision),
  });
  expect([200, 202]).toContain(signalled.status);
  const completed = await waitForStage(token, id, ['COMPLETED']);
  expect(completed.artifact_id).toBeTruthy();
  const published = await api(token, `/api/v1/commissions/${id}/publications`, {
    method: 'POST',
  });
  expect(published.status).toBe(201);
  const publicationId = published.body.publication_id;

  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  page.on('console', (message) => {
    if (message.type() === 'error') errors.push(message.text());
  });
  await page.goto(`/?record=${publicationId}`);
  await page.locator('#history').scrollIntoViewIfNeeded();
  await expect(page.locator('.record-title')).toContainText(
    'Record integration',
  );
  await expect(page.locator('.record-note')).toContainText(
    'Authoritative record',
  );
  const types = await page.locator('.ledger-type').allTextContents();
  for (const expected of [
    'commission.received',
    'run.started',
    'step.completed',
    'revision.created',
    'approval.requested',
    'decision.recorded',
    'artifact.recorded',
    'workflow.completed',
  ]) {
    expect(types).toContain(expected);
  }
  await expect(page.locator('.ledger li[data-kind="decision"]')).toHaveCount(1);
  await expect(page.locator('#record')).not.toContainText(access.token);
  await expect(page.locator('#record')).not.toContainText('local-commissioner');
  await page.screenshot({
    path: testInfo.outputPath('record.png'),
    fullPage: false,
  });
  expect(errors).toEqual([]);
});
