apiVersion: v1
kind: ServiceAccount
metadata:
  name: velin-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velin-worker
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velin-capabilities
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velin-frontend
automountServiceAccountToken: false
